-- CREATE TABLE

-- 도로명 임시 테이블 생성
CREATE TABLE TB_RN_TMP(
    RN_CD VARCHAR2(12) NOT NULL, -- 도로명 코드
    RN VARCHAR2(150) NOT NULL -- 도로명
);

-- 지하철역 임시 테이블 생성
CREATE TABLE TB_SUBWAY_STATN_TMP(
    SUBWAY_STATN_NO CHAR(6) NOT NULL, -- 지하철역 번호
    LN_NM VARCHAR2(50) NOT NULL, -- 노선명
    STATN_NM VARCHAR2(50) NOT NULL, -- 역명
    -- 지하철역 번호를 PK로 지정
    CONSTRAINT PK_TB_SUBWAY_STATN_TMP PRIMARY KEY(SUBWAY_STATN_NO)
);

-- 지하철역 승하차 임시 테이블 생성
-- 지하철역임시의 자식 테이블
CREATE TABLE TB_SUBWAY_STATN_TK_GFF_TMP(
    SUBWAY_STATN_NO CHAR(6) NOT NULL, -- 지하철역 번호
    STD_YM CHAR(6) NOT NULL, -- 기준년월
    BEGIN_TIME CHAR(4) NOT NULL, -- 시작시간
    END_TIME CHAR(4) NOT NULL, -- 종료시간
    TK_GFF_SE_CD VARCHAR2(6) NOT NULL, -- 승하차구분코드
    TK_GFF_CNT NUMBER(15) NOT NULL, -- 승하차횟수
    CONSTRAINT PK_TB_SUBWAY_STATN_TK_GFF_TMP PRIMARY KEY(SUBWAY_STATN_NO, STD_YM, BEGIN_TIME, END_TIME, TK_GFF_SE_CD)
);

-- 지하철역승하차임시 테이블에 참조 무결성 제약조건(FK)을 생성
ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP
ADD CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1
-- 지하철역승하차임시 테이블의 지하철역번호 칼럼은 지하철역임시 테이블의 지하철역번호를 참조
FOREIGN KEY(SUBWAY_STATN_NO) REFERENCES TB_SUBWAY_STATN_TMP(SUBWAY_STATN_NO);

-- ALTER TABLE
ALTER TABLE TB_SUBWAY_STATN_TMP ADD (OPER_YN CHAR(1)); -- 운영여부 칼럼 추가

ALTER TABLE TB_SUBWAY_STATN_TMP DROP COLUMN OPER_YN; -- 운영여부 칼럼 제거

-- 운영여부 칼럼 추가 생성
ALTER TABLE TB_SUBWAY_STATN_TMP ADD (OPER_YN CHAR(1));

-- 운영여부 칼럼 변경
ALTER TABLE TB_SUBWAY_STATN_TMP MODIFY(OPER_YN NUMBER(1) DEFAULT 0 NOT NULL NOVALIDATE);
-- 제약조건 MODIFY 작업 시 NOVALIDATE 옵션을 주면 해당 칼럼의 값에 NULL이 있어도 NOT NULL 제약 조건으로 변경 가능
-- 하지만 이후에 들어오는 데이터는 반드시 NULL이 아니어야 한다

-- 칼럼 이름 변경
ALTER TABLE TB_SUBWAY_STATN_TMP 
RENAME COLUMN OPER_YN TO OPERATION_YN;

-- 외래키 제거
ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP
DROP CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1;

-- 외래키 생성
ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP
ADD CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1
FOREIGN KEY(SUBWAY_STATN_NO) REFERENCES TB_SUBWAY_STATN_TMP(SUBWAY_STATN_NO);

-- 테이블명 변경
RENAME TB_SUBWAY_STATN_TK_GFF_TMP TO TB_SUBWAY_STATN_TK_GFF_TMP_2;

SELECT * FROM TB_SUBWAY_STATN_TK_GFF_TMP_2;

-- 테이블 내 데이터 제거
TRUNCATE TABLE TB_SUBWAY_STATN_TK_GFF_TMP_2;
-- 잘렸습니다 : ROLLBACK으로 복구되지 않음
-- 테이블 객체는 두고 내부의 데이터만 영구적으로 제거

-- 테이블 제거
DROP TABLE TB_SUBWAY_STATN_TK_GFF_TMP_2;
DROP TABLE TB_SUBWAY_STATN_TMP;
DROP TABLE TB_RN_TMP;




