server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: apigateway # localhost:8000/first-service로 접근하면 first service로 포워딩이 됨
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE # lb : 로드밸런싱 -> first-service의 application.yml 주소를 받아옴 lb를 작성하지 않는 경우 직접 작성해주면 됨
          predicates:
            - Path=/first-service/**
        - id: second-service
          url: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**
  main:
    web-application-type: reactive